In [2]:
import quandl
import pandas as pd
import numpy as np
from datetime import datetime
from pytz import timezone
import pytz

In [3]:
quandl.ApiConfig.api_key = "sXju3Jbujdoy1eqBMaBy"

In [4]:
def get_pst_time():
    date_format='%Y-%m-%d %H:%M:%S %z'
    date = datetime.now(tz=pytz.utc)
    date = date.astimezone(timezone('US/Pacific'))
    pstDateTime=date.strftime(date_format)
    pstDateTime = "{0}:{1}".format(pstDateTime[:-2],pstDateTime[-2:])
    return pstDateTime

In [5]:
table = quandl.get_table('FXCM/H1', date='2022-01-14', symbol='AUD/USD,CAD/JPY')
table.head()

,symbol,date,hour,openbid,highbid,lowbid,closebid,openask,highask,lowask,closeask,totalticks
None,,,,,,,,,,,,
0,AUD/USD,2022-01-14,0,0.72811,0.72811,0.72712,0.72763,0.72814,0.72814,0.72713,0.72763,4983
1,AUD/USD,2022-01-14,1,0.72763,0.72796,0.72649,0.72670,0.72763,0.72797,0.72651,0.72672,8188
2,AUD/USD,2022-01-14,2,0.72670,0.72752,0.72650,0.72752,0.72672,0.72754,0.72652,0.72753,5664
3,AUD/USD,2022-01-14,3,0.72752,0.72756,0.72693,0.72746,0.72753,0.72758,0.72694,0.72747,3951
4,AUD/USD,2022-01-14,4,0.72746,0.72835,0.72746,0.72823,0.72747,0.72837,0.72747,0.72825,3718

In [6]:
table = quandl.get_table('FXCM/H1', date='2021-01-21', symbol='AUD/USD,CAD/JPY')

table['date'] = table['date'].astype(str) + " "+ table['hour'].apply(lambda x: '00:0' if x < 10 else '00:') + table['hour'].astype(str) + ":00 +00:00"
formattedTable = table[['date', 'symbol', 'openbid', 'highbid', 'lowbid', 'closebid', 'totalticks']].copy()
formattedTable.columns = formattedTable.columns.str.capitalize()
formattedTable.set_index('Date', inplace=True)

formattedTable['Engine'] = float("NaN")
formattedTable['Source'] = "Quandl"
formattedTable['Update'] = get_pst_time()
formattedTable.head(20)

,Symbol,Openbid,Highbid,Lowbid,Closebid,Totalticks,Engine,Source,Update
Date,,,,,,,,,
2021-01-21 00:00:00 +00:00,AUD/USD,0.77547,0.77596,0.77488,0.77573,9565,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:01:00 +00:00,AUD/USD,0.77573,0.77731,0.77550,0.77656,12333,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:02:00 +00:00,AUD/USD,0.77656,0.77761,0.77644,0.77720,10368,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:03:00 +00:00,AUD/USD,0.77720,0.77772,0.77689,0.77759,11128,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:04:00 +00:00,AUD/USD,0.77759,0.77761,0.77669,0.77696,7754,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:05:00 +00:00,AUD/USD,0.77696,0.77770,0.77687,0.77752,8375,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:06:00 +00:00,AUD/USD,0.77752,0.77752,0.77660,0.77698,8705,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:07:00 +00:00,AUD/USD,0.77698,0.77713,0.77559,0.77583,9567,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:08:00 +00:00,AUD/USD,0.77583,0.77666,0.77515,0.77626,13879,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:09:00 +00:00,AUD/USD,0.77626,0.77750,0.77617,0.77736,10352,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:10:00 +00:00,AUD/USD,0.77736,0.77748,0.77682,0.77741,7422,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:11:00 +00:00,AUD/USD,0.77741,0.77750,0.77654,0.77739,7360,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:12:00 +00:00,AUD/USD,0.77739,0.77824,0.77714,0.77716,8345,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:13:00 +00:00,AUD/USD,0.77716,0.77801,0.77596,0.77598,18091,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:14:00 +00:00,AUD/USD,0.77598,0.77692,0.77543,0.77607,19029,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:15:00 +00:00,AUD/USD,0.77607,0.77754,0.77587,0.77641,14297,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:16:00 +00:00,AUD/USD,0.77641,0.77710,0.77473,0.77538,10955,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:17:00 +00:00,AUD/USD,0.77538,0.77538,0.77414,0.77484,9346,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:18:00 +00:00,AUD/USD,0.77484,0.77554,0.77476,0.77539,6904,NaN,Quandl,2022-03-04 17:04:05 -08:00
2021-01-21 00:00:00 +00:00,CAD/JPY,81.99900,82.11300,81.98500,82.08500,4978,NaN,Quandl,2022-03-04 17:04:05 -08:00

In [9]:
aapl = quandl.get("EOD/MS", authtoken="sXju3Jbujdoy1eqBMaBy")
aapl

,Open,High,Low,Close,Volume,Dividend,Split,Adj_Open,Adj_High,Adj_Low,Adj_Close,Adj_Volume
Date,,,,,,,,,,,,
1980-12-12,28.750,28.870,28.7500,28.75,2093900.0,0.0,1.0,0.100850,0.101271,0.100850,0.100850,469033600.0
1980-12-15,27.380,27.380,27.2500,27.25,785200.0,0.0,1.0,0.096044,0.096044,0.095588,0.095588,175884800.0
1980-12-16,25.370,25.370,25.2500,25.25,472000.0,0.0,1.0,0.088993,0.088993,0.088572,0.088572,105728000.0
1980-12-17,25.870,26.000,25.8700,25.87,385900.0,0.0,1.0,0.090747,0.091203,0.090747,0.090747,86441600.0
1980-12-18,26.630,26.750,26.6300,26.63,327900.0,0.0,1.0,0.093413,0.093834,0.093413,0.093413,73449600.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-25,148.680,149.370,147.6211,148.64,50376102.0,0.0,1.0,148.680000,149.370000,147.621100,148.640000,50376102.0
2021-10-26,149.330,150.840,149.0101,149.32,60630899.0,0.0,1.0,149.330000,150.840000,149.010100,149.320000,60630899.0
2021-10-27,149.360,149.730,148.4900,148.85,55786500.0,0.0,1.0,149.360000,149.730000,148.490000,148.850000,55786500.0
2021-10-28,149.820,153.165,149.7200,152.57,95522214.0,0.0,1.0,149.820000,153.165000,149.720000,152.570000,95522214.0
2021-10-29,147.215,149.940,146.4128,149.80,120521424.0,0.0,1.0,147.215000,149.940000,146.412800,149.800000,120521424.0

In [8]:
table = quandl.get("EOD/AAPL", authtoken="sXju3Jbujdoy1eqBMaBy")
#table['date'] = table['date'].astype(str) + " "+ table['hour'].apply(lambda x: '00:0' if x < 10 else '00:') + table['hour'].astype(str) + ":00 +00:00"
formattedTable = table[['Adj_Open', 'Adj_High', 'Adj_Low', 'Adj_Close', 'Adj_Volume']].copy()
#formattedTable.set_index('Date', inplace=True)

formattedTable['Engine'] = float("NaN")
formattedTable['Source'] = "Quandl"
formattedTable['Update'] = get_pst_time()
formattedTable.head(20)

,Adj_Open,Adj_High,Adj_Low,Adj_Close,Adj_Volume,Engine,Source,Update
Date,,,,,,,,
1980-12-12,0.100850,0.101271,0.100850,0.100850,469033600.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-15,0.096044,0.096044,0.095588,0.095588,175884800.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-16,0.088993,0.088993,0.088572,0.088572,105728000.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-17,0.090747,0.091203,0.090747,0.090747,86441600.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-18,0.093413,0.093834,0.093413,0.093413,73449600.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-19,0.099096,0.099552,0.099096,0.099096,48630400.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-22,0.103937,0.104357,0.103937,0.103937,37363200.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-23,0.108321,0.108742,0.108321,0.108321,46950400.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-24,0.114004,0.114460,0.114004,0.114004,48003200.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-26,0.124527,0.124948,0.124527,0.124527,55574400.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-29,0.126281,0.126737,0.126281,0.126281,93161600.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-30,0.123650,0.123650,0.123194,0.123194,68880000.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1980-12-31,0.120143,0.120143,0.119722,0.119722,35750400.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1981-01-02,0.121020,0.121897,0.121020,0.121020,21660800.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1981-01-05,0.118810,0.118810,0.118389,0.118389,35728000.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1981-01-06,0.113548,0.113548,0.113127,0.113127,45158400.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1981-01-07,0.108742,0.108742,0.108321,0.108321,55686400.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1981-01-08,0.106532,0.106532,0.106111,0.106111,39827200.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1981-01-09,0.111829,0.112250,0.111829,0.111829,21504000.0,NaN,Quandl,2022-03-04 17:04:15 -08:00
1981-01-12,0.111829,0.111829,0.110917,0.110917,23699200.0,NaN,Quandl,2022-03-04 17:04:15 -08:00